// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/dsmovetools2d.h"
#include <Rcpp.h>

using namespace Rcpp;

// TestCTDS2DDomainIO
NumericMatrix TestCTDS2DDomainIO(std::vector<double> lons, std::vector<double> lats, std::vector<double> surface_heights, NumericMatrix init_dsts, NumericMatrix init_srcs, std::vector<double> log_probs);
RcppExport SEXP _dsmovetools2d_TestCTDS2DDomainIO(SEXP lonsSEXP, SEXP latsSEXP, SEXP surface_heightsSEXP, SEXP init_dstsSEXP, SEXP init_srcsSEXP, SEXP log_probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type lons(lonsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type surface_heights(surface_heightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_dsts(init_dstsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_srcs(init_srcsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type log_probs(log_probsSEXP);
    rcpp_result_gen = Rcpp::wrap(TestCTDS2DDomainIO(lons, lats, surface_heights, init_dsts, init_srcs, log_probs));
    return rcpp_result_gen;
END_RCPP
}
// LogTxProbs
NumericMatrix LogTxProbs(std::vector<double> lons, std::vector<double> lats, std::vector<double> surface_heights, int lon_from_ind, int lat_from_ind, int lon_to_ind, int lat_to_ind, double betaAR);
RcppExport SEXP _dsmovetools2d_LogTxProbs(SEXP lonsSEXP, SEXP latsSEXP, SEXP surface_heightsSEXP, SEXP lon_from_indSEXP, SEXP lat_from_indSEXP, SEXP lon_to_indSEXP, SEXP lat_to_indSEXP, SEXP betaARSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type lons(lonsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type surface_heights(surface_heightsSEXP);
    Rcpp::traits::input_parameter< int >::type lon_from_ind(lon_from_indSEXP);
    Rcpp::traits::input_parameter< int >::type lat_from_ind(lat_from_indSEXP);
    Rcpp::traits::input_parameter< int >::type lon_to_ind(lon_to_indSEXP);
    Rcpp::traits::input_parameter< int >::type lat_to_ind(lat_to_indSEXP);
    Rcpp::traits::input_parameter< double >::type betaAR(betaARSEXP);
    rcpp_result_gen = Rcpp::wrap(LogTxProbs(lons, lats, surface_heights, lon_from_ind, lat_from_ind, lon_to_ind, lat_to_ind, betaAR));
    return rcpp_result_gen;
END_RCPP
}
// FF_DTMC
NumericMatrix FF_DTMC(std::vector<double> lons, std::vector<double> lats, std::vector<double> surface_heights, NumericMatrix init_dsts, NumericMatrix init_srcs, std::vector<double> init_log_probs, unsigned int steps, double log_self_tx, double betaAR);
RcppExport SEXP _dsmovetools2d_FF_DTMC(SEXP lonsSEXP, SEXP latsSEXP, SEXP surface_heightsSEXP, SEXP init_dstsSEXP, SEXP init_srcsSEXP, SEXP init_log_probsSEXP, SEXP stepsSEXP, SEXP log_self_txSEXP, SEXP betaARSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type lons(lonsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type surface_heights(surface_heightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_dsts(init_dstsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_srcs(init_srcsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type init_log_probs(init_log_probsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< double >::type log_self_tx(log_self_txSEXP);
    Rcpp::traits::input_parameter< double >::type betaAR(betaARSEXP);
    rcpp_result_gen = Rcpp::wrap(FF_DTMC(lons, lats, surface_heights, init_dsts, init_srcs, init_log_probs, steps, log_self_tx, betaAR));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dsmovetools2d_TestCTDS2DDomainIO", (DL_FUNC) &_dsmovetools2d_TestCTDS2DDomainIO, 6},
    {"_dsmovetools2d_LogTxProbs", (DL_FUNC) &_dsmovetools2d_LogTxProbs, 8},
    {"_dsmovetools2d_FF_DTMC", (DL_FUNC) &_dsmovetools2d_FF_DTMC, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_dsmovetools2d(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
