# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TestCTDS2DDomainIO <- function(lons, lats, surface_heights, init_dsts, init_srcs, log_probs) {
    .Call('_dsmovetools2d_TestCTDS2DDomainIO', PACKAGE = 'dsmovetools2d', lons, lats, surface_heights, init_dsts, init_srcs, log_probs)
}

