# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TestRookNeighborhood <- function(dims, x) {
    .Call('_dsmovetools_TestRookNeighborhood', PACKAGE = 'dsmovetools', dims, x)
}

TestSparseNdimArrayReadWrite <- function(coords, values) {
    .Call('_dsmovetools_TestSparseNdimArrayReadWrite', PACKAGE = 'dsmovetools', coords, values)
}

TestFFRW <- function(a0coords, a0values, dims, steps) {
    .Call('_dsmovetools_TestFFRW', PACKAGE = 'dsmovetools', a0coords, a0values, dims, steps)
}

TestFFRWLight <- function(a0coords, a0values, dims, steps) {
    .Call('_dsmovetools_TestFFRWLight', PACKAGE = 'dsmovetools', a0coords, a0values, dims, steps)
}

TestFFRWLightLog <- function(a0coords, log_a0values, dims, steps) {
    .Call('_dsmovetools_TestFFRWLightLog', PACKAGE = 'dsmovetools', a0coords, log_a0values, dims, steps)
}

