# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TestRookOrientation <- function(head, tail) {
    .Call('_dsmovetools_TestRookOrientation', PACKAGE = 'dsmovetools', head, tail)
}

TestRookDot <- function(head, tail, nextHead) {
    .Call('_dsmovetools_TestRookDot', PACKAGE = 'dsmovetools', head, tail, nextHead)
}

TestRookNeighborhood <- function(dims, x) {
    .Call('_dsmovetools_TestRookNeighborhood', PACKAGE = 'dsmovetools', dims, x)
}

TestSparseNdimArrayReadWrite <- function(coords, values) {
    .Call('_dsmovetools_TestSparseNdimArrayReadWrite', PACKAGE = 'dsmovetools', coords, values)
}

TestBivariateSparseNdimArrayReadWrite <- function(coords1, coords2, values) {
    .Call('_dsmovetools_TestBivariateSparseNdimArrayReadWrite', PACKAGE = 'dsmovetools', coords1, coords2, values)
}

TestSparseNdimArrayHash <- function(coords1, coords2, values) {
    .Call('_dsmovetools_TestSparseNdimArrayHash', PACKAGE = 'dsmovetools', coords1, coords2, values)
}

TxModelParams <- function(cur_loc, prev_loc, dims, betaAR) {
    .Call('_dsmovetools_TxModelParams', PACKAGE = 'dsmovetools', cur_loc, prev_loc, dims, betaAR)
}

TxModelSample <- function(cur_loc, prev_loc, dims, betaAR) {
    .Call('_dsmovetools_TxModelSample', PACKAGE = 'dsmovetools', cur_loc, prev_loc, dims, betaAR)
}

TxModelLd <- function(cur_loc, prev_loc, dims, betaAR, dst_loc) {
    .Call('_dsmovetools_TxModelLd', PACKAGE = 'dsmovetools', cur_loc, prev_loc, dims, betaAR, dst_loc)
}

TestZConstrainedRookNeighborhood <- function(dims, x, zfield, zvals) {
    .Call('_dsmovetools_TestZConstrainedRookNeighborhood', PACKAGE = 'dsmovetools', dims, x, zfield, zvals)
}

SampleConstrainedBridgedRWPath <- function(a0coords, dstcoords, dims, steps, max_steps, surface_heights, domain_heights) {
    .Call('_dsmovetools_SampleConstrainedBridgedRWPath', PACKAGE = 'dsmovetools', a0coords, dstcoords, dims, steps, max_steps, surface_heights, domain_heights)
}

SampleConstrainedBridgedRWPathFamily <- function(a0coords, dstcoords, dims, steps, max_steps, surface_heights, domain_heights, n) {
    .Call('_dsmovetools_SampleConstrainedBridgedRWPathFamily', PACKAGE = 'dsmovetools', a0coords, dstcoords, dims, steps, max_steps, surface_heights, domain_heights, n)
}

FFRWLightLogConstrainedSelfTxAR <- function(a0, a0_prev_coords, log_a0val, dims, steps, surface_heights, domain_heights, log_self_tx, betaAR) {
    .Call('_dsmovetools_FFRWLightLogConstrainedSelfTxAR', PACKAGE = 'dsmovetools', a0, a0_prev_coords, log_a0val, dims, steps, surface_heights, domain_heights, log_self_tx, betaAR)
}

ARFilteredLL <- function(a0, a0_prev_coords, obs_coords, log_a0val, dims, surface_heights, domain_heights, log_self_tx, betaAR) {
    .Call('_dsmovetools_ARFilteredLL', PACKAGE = 'dsmovetools', a0, a0_prev_coords, obs_coords, log_a0val, dims, surface_heights, domain_heights, log_self_tx, betaAR)
}

ARPredDist <- function(a0, a0_prev_coords, obs_coords, log_a0val, dims, surface_heights, domain_heights, log_self_tx, betaAR, pred_steps) {
    .Call('_dsmovetools_ARPredDist', PACKAGE = 'dsmovetools', a0, a0_prev_coords, obs_coords, log_a0val, dims, surface_heights, domain_heights, log_self_tx, betaAR, pred_steps)
}

ARBackInfoFilteringDist <- function(a0, a0_prev_coords, obs_coords, log_a0val, dims, surface_heights, domain_heights, log_self_tx, betaAR, pred_steps) {
    .Call('_dsmovetools_ARBackInfoFilteringDist', PACKAGE = 'dsmovetools', a0, a0_prev_coords, obs_coords, log_a0val, dims, surface_heights, domain_heights, log_self_tx, betaAR, pred_steps)
}

TestFFRW <- function(a0coords, a0values, dims, steps) {
    .Call('_dsmovetools_TestFFRW', PACKAGE = 'dsmovetools', a0coords, a0values, dims, steps)
}

TestFFRWLight <- function(a0coords, a0values, dims, steps) {
    .Call('_dsmovetools_TestFFRWLight', PACKAGE = 'dsmovetools', a0coords, a0values, dims, steps)
}

TestFFRWLightLog <- function(a0coords, log_a0values, dims, steps) {
    .Call('_dsmovetools_TestFFRWLightLog', PACKAGE = 'dsmovetools', a0coords, log_a0values, dims, steps)
}

FFRWLightLogConstrained <- function(a0coords, log_a0values, dims, steps, surface_heights, domain_heights) {
    .Call('_dsmovetools_FFRWLightLogConstrained', PACKAGE = 'dsmovetools', a0coords, log_a0values, dims, steps, surface_heights, domain_heights)
}

FFRWLightLogConstrainedSelfTx <- function(a0coords, log_a0values, dims, steps, surface_heights, domain_heights, log_self_tx) {
    .Call('_dsmovetools_FFRWLightLogConstrainedSelfTx', PACKAGE = 'dsmovetools', a0coords, log_a0values, dims, steps, surface_heights, domain_heights, log_self_tx)
}

FFRWLogConstrained <- function(a0coords, log_a0values, dims, steps, surface_heights, domain_heights) {
    .Call('_dsmovetools_FFRWLogConstrained', PACKAGE = 'dsmovetools', a0coords, log_a0values, dims, steps, surface_heights, domain_heights)
}

FFRWLogConstrainedDst <- function(a0coords, dstcoords, log_a0values, dims, steps, max_steps, surface_heights, domain_heights) {
    .Call('_dsmovetools_FFRWLogConstrainedDst', PACKAGE = 'dsmovetools', a0coords, dstcoords, log_a0values, dims, steps, max_steps, surface_heights, domain_heights)
}

FFRWLogConstrainedDstReachable <- function(a0coords, dstcoords, log_a0values, dims, steps, max_steps, surface_heights, domain_heights) {
    .Call('_dsmovetools_FFRWLogConstrainedDstReachable', PACKAGE = 'dsmovetools', a0coords, dstcoords, log_a0values, dims, steps, max_steps, surface_heights, domain_heights)
}

